# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
print(np.__version__)
print(np.show_config)

1.21.6
<function show at 0x7f95badfc440>


#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
x=np.zeros(10)
print(x)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
a=np.array([2,3,4,6,5])
a.size

5

In [ ]:
a=np.array([2,3,4,6,5])

#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [ ]:
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10)
x[5]=1
x

array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.])

#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
a=np.array(range(10,50))
a

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
a=np.array(range(10,50))
a[::-1]

array([49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33,
       32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16,
       15, 14, 13, 12, 11, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a=np.array(range(0,9))
a.reshape(3,3)

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=[1,2,0,0,4,0]
np.nonzero(a)

(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3,3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
a=np.random.random((3,3,3))
a

array([[[0.49264847, 0.63107952, 0.16222023],
        [0.88257176, 0.99302276, 0.87327052],
        [0.04951929, 0.91405239, 0.67769411]],

       [[0.8442894 , 0.10925336, 0.58649054],
        [0.46566259, 0.19137017, 0.72344131],
        [0.78639766, 0.1609334 , 0.18849259]],

       [[0.12336842, 0.41258573, 0.38674286],
        [0.75901738, 0.8578554 , 0.22235275],
        [0.12281267, 0.08619878, 0.98304431]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
a=np.random.random((10,10))
print(np.min(a))
print(np.max(a))
print(a)

0.006792908564247524
0.9990253429743727
[[0.32410695 0.60459711 0.1269493  0.17877691 0.58851428 0.24970637
  0.81478336 0.27105356 0.95932997 0.65805501]
 [0.60210452 0.20136888 0.20282093 0.30566756 0.66134242 0.30315967
  0.56137826 0.78471013 0.27867843 0.61626446]
 [0.30835805 0.0668973  0.29465131 0.45288062 0.84905875 0.33416125
  0.03901996 0.47918696 0.24331378 0.49063198]
 [0.84123652 0.1227436  0.8079974  0.58468043 0.39692172 0.13469998
  0.87489998 0.14569205 0.80507993 0.19384622]
 [0.61755828 0.83339954 0.44372836 0.1968136  0.10765384 0.21820613
  0.63755789 0.85103788 0.21686819 0.99520352]
 [0.99902534 0.05782621 0.25701012 0.85767319 0.7898441  0.09222219
  0.1442913  0.74375897 0.30060109 0.54303921]
 [0.31683154 0.91294094 0.92975069 0.47926753 0.55086931 0.50407726
  0.60334032 0.6785112  0.1903575  0.72793085]
 [0.15155156 0.36968543 0.13062957 0.99351829 0.90650615 0.75368031
  0.8006673  0.81657032 0.43716068 0.00679291]
 [0.68463709 0.0533687  0.55283533 0.866

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
a=np.random.rand(30)
print(np.mean(a))
print(a)

0.3605661879780259
[0.0197117  0.13360657 0.0166745  0.03820266 0.56145241 0.13438282
 0.78803061 0.52389601 0.60598133 0.1002499  0.3933733  0.39720518
 0.00751005 0.53136961 0.73411732 0.22964993 0.29942685 0.90192781
 0.06353702 0.27483883 0.07888067 0.74673184 0.38707953 0.40594664
 0.08188108 0.52539245 0.72397286 0.47573737 0.55756311 0.07865567]


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
import numpy as np
x=np.ones((5,5))
x[1:-1,1:-1]=0
x

array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
import numpy as np
x=np.ones((5,5))
y=np.pad(x,pad_width=1,mode="constant",constant_values=0)
y

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 1., 1., 1., 1., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
NaN
False
False
NaN
False

NameError: ignored

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
import numpy as np
x=np.ones((5,5))
x+=np.arange(5)
x

array([[1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.],
       [1., 2., 3., 4., 5.]])

#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
import numpy as np
x=np.ones((3,3))
x=np.zeros((8,8),dtype=int)
x[1::2,::2]=1
x[::2,1::2]=1
x

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:
np.unravel_index(100,(6,7,8))

(1, 5, 4)

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:
a=np.array([[0,1],[1,0]])
y=np.tile(a,(4,4))
y

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
x=np.random.random((5,5))
xmax,xmin=x.max(),x.min()
x=(x-xmin)/(xmax-xmin)
x

array([[0.19298488, 0.        , 0.88091321, 0.83606017, 0.98925649],
       [0.86810106, 0.68825874, 0.58138773, 0.41480673, 0.92645858],
       [0.82641573, 0.53496751, 0.783882  , 0.7666982 , 0.99297154],
       [0.9117495 , 0.75228544, 0.34973044, 0.19526951, 0.2375831 ],
       [0.98961617, 1.        , 0.22074034, 0.01046126, 0.55006006]])

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
RGBA = np.dtype([('red',np.uint8),('green',np.uint8),('blue',np.uint8),('alpha',np.uint8)])
color = np.array((1,2,4,3),dtype = RGBA)
print(color['red'])
type(color)

1


numpy.ndarray

#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
x=np.dot(np.ones((5,3)),np.ones((3,2)))
x

array([[3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.],
       [3., 3.]])

#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
arr=np.arange(16)
print(arr>=3)
arr[(arr>=3) & (arr<=8)]*=(-1)
print(arr)

[False False False  True  True  True  True  True  True  True  True  True
  True  True  True  True]
[ 0  1  2 -3 -4 -5 -6 -7 -8  9 10 11 12 13 14 15]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
9
10

10

#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z = arange(10)
Z**Z
Z_2 = 2 << Z >> 2
Z_2
print([bin(2) for z in Z_2])
print([bin(z) for z in 2 << Z_2])
print([bin(z) for z in Z_2])
Z<Z>Z

NameError: ignored

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array([np.nan]).astype(int).astype(float)

array([-9.22337204e+18])

#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
arr=np.random.random((5,5))
print(arr)
arr=np.round(arr,2)
print(arr)

[[0.52415255 0.39504145 0.75770417 0.98805177 0.55918763]
 [0.97286812 0.79860468 0.03876054 0.8113896  0.95622575]
 [0.70136392 0.49750581 0.40909888 0.06416765 0.59100547]
 [0.87851865 0.34686254 0.6653533  0.23483142 0.55812295]
 [0.05211004 0.92685721 0.36791594 0.98585369 0.8139832 ]]
[[0.52 0.4  0.76 0.99 0.56]
 [0.97 0.8  0.04 0.81 0.96]
 [0.7  0.5  0.41 0.06 0.59]
 [0.88 0.35 0.67 0.23 0.56]
 [0.05 0.93 0.37 0.99 0.81]]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
x=np.array([1,2,3,4])
y=np.array([2,3,1,9])
print(np.intersect1d(x,y))

[1 2 3]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
import numpy as np
data=np.random.random(1000).reshape(10,10,10)*np.nan
np.seterr(all="ignore")

{'divide': 'warn', 'over': 'warn', 'under': 'ignore', 'invalid': 'warn'}

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')

#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
C = np.ones(3)*3
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.dot(A,B)

-4.5

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print (np.floor(Z))
print (np.ceil(Z)-1)
print (Z.astype(int))

[2. 3. 1. 1. 0. 7. 1. 3. 3. 8.]
[2. 3. 1. 1. 0. 7. 1. 3. 3. 8.]
[2. 3. 1. 1. 0. 7. 1. 3. 3. 8.]
[2 3 1 1 0 7 1 3 3 8]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
x=np.zeros((5,5))
x+=np.arange(5)
x

array([[0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.],
       [0., 1., 2., 3., 4.]])

#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def forma():
    for i in range(10):
        yield i
x=np.fromiter(forma(),dtype=float,count=-1)
x        

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
np.linspace(0,1,12,endpoint=True)[1:-1]

array([0.09090909, 0.18181818, 0.27272727, 0.36363636, 0.45454545,
       0.54545455, 0.63636364, 0.72727273, 0.81818182, 0.90909091])

#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
np.random.random(10)
x.sort()
x

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
x=np.random.random((5,5))
np.add.reduce(x,dtype=float)

array([2.35579233, 3.21755737, 2.48800555, 1.70976997, 2.68979325])

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
x=np.random.randint(0,2,5)
y=np.random.randint(0,2,5)
e=np.allclose(x,y)
e

False

#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
Z = np.zeros(10)
Z.flags.writeable = False

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
x=np.random.random((10,2))
a,b=x[:,0],x[:,1]
y=np.sqrt(a**2+b**2)
t=np.arctan2(b,a)
y,t

(array([0.6782751 , 0.79790631, 0.28420162, 0.66197078, 0.46366122,
        1.20666977, 0.49239185, 0.53912053, 1.22545154, 0.8529474 ]),
 array([0.02593956, 1.12668421, 0.2465963 , 0.89810842, 0.87197894,
        0.69584284, 0.34625138, 1.04297263, 0.67224431, 0.54320557]))

#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x=np.random.random(10)
x[x.argmax()]=0
x

array([0.67675334, 0.33279368, 0.        , 0.37850116, 0.83296938,
       0.8101152 , 0.66138757, 0.6600239 , 0.3792509 , 0.78669021])

#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
# X = np.random.randint(0,11,(5,5))
# Y = np.random.randint(11,22,(5,5))
# C = 1/(Y-X.T)
# C

Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
#print(X)
X  = np.tile(X,(10,1)).T
#print(X)

C = 1/(X - Y)
C

array([[0.05882353, 0.125     , 0.07692308, 0.07142857, 0.08333333,
        0.11111111, 0.125     , 0.11111111, 0.09090909, 0.11111111],
       [0.04761905, 0.08333333, 0.05882353, 0.05555556, 0.0625    ,
        0.07692308, 0.08333333, 0.07692308, 0.06666667, 0.07692308],
       [0.07692308, 0.25      , 0.11111111, 0.1       , 0.125     ,
        0.2       , 0.25      , 0.2       , 0.14285714, 0.2       ],
       [0.05      , 0.09090909, 0.0625    , 0.05882353, 0.06666667,
        0.08333333, 0.09090909, 0.08333333, 0.07142857, 0.08333333],
       [0.06666667, 0.16666667, 0.09090909, 0.08333333, 0.1       ,
        0.14285714, 0.16666667, 0.14285714, 0.11111111, 0.14285714],
       [0.07692308, 0.25      , 0.11111111, 0.1       , 0.125     ,
        0.2       , 0.25      , 0.2       , 0.14285714, 0.2       ],
       [0.05      , 0.09090909, 0.0625    , 0.05882353, 0.06666667,
        0.08333333, 0.09090909, 0.08333333, 0.07142857, 0.08333333],
       [0.06666667, 0.16666667, 0.0909090

####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
# X = np.random.randint(0,11,(5,5))
# Y = np.random.randint(11,22,(5,5))
# C = 1/(Y-X.T)
# C

Y = np.random.randint(0,11,10)
X = np.random.randint(11,22,10)
#print(Y.reshape(1,10))
Y = np.tile(Y,(10,1))
#print(X)
X  = np.tile(X,(10,1)).T
#print(X)

C = 1/(X - Y)
C

array([[0.07142857, 0.0625    , 0.04761905, 0.05      , 0.04761905,
        0.05555556, 0.05263158, 0.05882353, 0.06666667, 0.04761905],
       [0.16666667, 0.125     , 0.07692308, 0.08333333, 0.07692308,
        0.1       , 0.09090909, 0.11111111, 0.14285714, 0.07692308],
       [0.16666667, 0.125     , 0.07692308, 0.08333333, 0.07692308,
        0.1       , 0.09090909, 0.11111111, 0.14285714, 0.07692308],
       [0.07142857, 0.0625    , 0.04761905, 0.05      , 0.04761905,
        0.05555556, 0.05263158, 0.05882353, 0.06666667, 0.04761905],
       [0.2       , 0.14285714, 0.08333333, 0.09090909, 0.08333333,
        0.11111111, 0.1       , 0.125     , 0.16666667, 0.08333333],
       [0.14285714, 0.11111111, 0.07142857, 0.07692308, 0.07142857,
        0.09090909, 0.08333333, 0.1       , 0.125     , 0.07142857],
       [0.09090909, 0.07692308, 0.05555556, 0.05882353, 0.05555556,
        0.06666667, 0.0625    , 0.07142857, 0.08333333, 0.05555556],
       [0.125     , 0.1       , 0.0666666

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
    print(np.iinfo(dtype).min)
    print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
    print(np.finfo(dtype).min)
    print(np.finfo(dtype).max)
    print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
#np.set_printoptions(threshold=np.nan)
#Z = np.zeros((int(1e4),int(1e4)))
Z = []
print(Z)

[]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
arr = np.random.uniform(0,10,10)
scal = 5
arr_1 = np.abs(arr - 5)
ind = arr_1.argmin()
print(arr)
print('*'*60)
print(arr[ind])

[8.11957964 9.15298782 3.17914027 1.74491264 7.70837006 3.86505753
 7.50038137 6.62058772 1.39627364 7.17084344]
************************************************************
3.86505753408688


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float),
                                  ('y', float)]),
                   ('color',    [ ('r', float),
                                  ('g', float),
                                  ('b', float)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
arr = np.random.random((100,2))
X,Y = np.atleast_2d(arr[:,0],arr[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

[[0.         0.54674882 0.41005336 0.15091581 0.31854476 0.64421624
  0.35003998 0.52157584 0.64734529 0.74344784]
 [0.54674882 0.         0.50978759 0.46930367 0.54572654 0.09749574
  0.64555725 0.36011631 0.44097811 0.69198676]
 [0.41005336 0.50978759 0.         0.26304515 0.11251681 0.5838534
  0.18566563 0.21664406 0.85009256 1.03545458]
 [0.15091581 0.46930367 0.26304515 0.         0.18539867 0.56466509
  0.24735662 0.3758601  0.67579565 0.81822267]
 [0.31854476 0.54572654 0.11251681 0.18539867 0.         0.63020926
  0.10044688 0.31083399 0.8342465  0.99621951]
 [0.64421624 0.09749574 0.5838534  0.56466509 0.63020926 0.
  0.73059501 0.41083568 0.46367659 0.72463802]
 [0.35003998 0.64555725 0.18566563 0.24735662 0.10044688 0.73059501
  0.         0.39972553 0.91785537 1.06526358]
 [0.52157584 0.36011631 0.21664406 0.3758601  0.31083399 0.41083568
  0.39972553 0.         0.76981356 0.99307088]
 [0.64734529 0.44097811 0.85009256 0.67579565 0.8342465  0.46367659
  0.91785537 0.769813

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = np.arange(10, dtype=np.float32)
Z_1 = Z.astype(np.float32, copy=False)
Z_1[0] = 2
print(Z)

[2. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:7: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  import sys


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
sigma,myu = 1.0,0.0

X,Y  = np.meshgrid(np.linspace(-1,1,10),np.linspace(-1,1,10))
D = np.sqrt(X**2+Y**2)
G = np.exp(-(D-myu)**2/(2*sigma**2))
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

np.put(Z,11,1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis = 1,keepdims = True)
#print(Y)
X.mean(axis = 1).reshape(-1,1) == X.mean(axis = 1,keepdims =True)

array([[ True],
       [ True],
       [ True],
       [ True],
       [ True]])

#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(5,5))
print(Z)


# Z_1 = Z
# for ind in range(5):
#     Z_1[:,ind].sort()
#print(Z_1)


print(Z[(-Z)[:,1].argsort()])
print(Z[:,Z[1,:].argsort()])

[[9 9 1 4 6]
 [9 1 6 8 4]
 [3 5 9 4 3]
 [6 0 4 9 7]
 [2 1 3 3 2]]
[[9 9 1 4 6]
 [3 5 9 4 3]
 [9 1 6 8 4]
 [2 1 3 3 2]
 [6 0 4 9 7]]
[[9 6 1 4 9]
 [1 4 6 8 9]
 [5 3 9 4 3]
 [0 7 4 9 6]
 [1 2 3 3 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
Z = np.random.randint(0,3,(3,10))
Z[:,1] = 0
Z = Z.astype(bool)
print(Z)
print(~Z)
(Z).any(axis = 0)

[[ True False False  True  True  True  True  True  True False]
 [ True False  True False  True False  True False  True False]
 [ True False  True  True  True  True  True  True False  True]]
[[False  True  True False False False False False False  True]
 [False  True False  True False  True False  True False  True]
 [False  True False False False False False False  True False]]


array([ True, False,  True,  True,  True,  True,  True,  True,  True,
        True])

#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
arr=np.array([8,7,1,5,3,4])
difarr=np.absolute(arr-2)
index=difarr.argmin()
print(arr[index])
print(index)

1
2


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
np.add.at(Z, I, 1)
print(Z)

[4. 3. 1. 2. 8. 2. 2. 1. 3. 4.]
[ 7.  5.  1.  3. 15.  3.  3.  1.  5.  7.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
 w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)


w, h = 256, 256
I = np.random.randint(0,4,(h,w,3), dtype=np.uint8)

# View each pixel as a single 24-bit integer, rather than three 8-bit bytes
I24 = np.dot(I.astype(np.uint32),[1,256,65536])

# Count unique colours
n = len(np.unique(I24))
print(n)

64
64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4)) 
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[56 43 49 46]
 [59 31 60 51]
 [54 61 58 44]]
[[56 43 49 46]
 [59 31 60 51]
 [54 61 58 44]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)
import pandas as pd
print(pd.Series(D).groupby(S).mean())

[0.39996216 0.52944385 0.41988734 0.6072918  0.48109398 0.55613223
 0.50410667 0.46577371 0.49549084 0.56571352]
0    0.399962
1    0.529444
2    0.419887
3    0.607292
4    0.481094
5    0.556132
6    0.504107
7    0.465774
8    0.495491
9    0.565714
dtype: float64


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)

array([1.05020858, 0.95201074, 0.76238908, 1.13721477, 0.57940551])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
Z = np.array([1,2,3,4,5])
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
A = np.ones((5,5,3))
B = 2*np.ones((5,5))
print(A * B[:,:,None])

[[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
A = np.arange(25).reshape(5,5)
A[[0,1]] = A[[1,0]]
print(A)

[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 0,  9) ( 0, 13) ( 2,  8) ( 2, 80) ( 8, 80) ( 9, 13) (12, 24) (12, 40)
 (16, 69) (16, 76) (24, 40) (25, 28) (25, 91) (28, 91) (45, 51) (45, 93)
 (47, 54) (47, 60) (47, 73) (47, 98) (49, 54) (49, 61) (51, 93) (52, 55)
 (52, 88) (54, 61) (54, 73) (55, 88) (60, 98) (69, 76)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

from numpy.lib.stride_tricks import sliding_window_view

Z = np.arange(20)
print(sliding_window_view(Z, window_shape=3).mean(axis=-1))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.strides[0], a.strides[0])
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

Z = np.arange(10)
print(sliding_window_view(Z, window_shape=3))

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]
[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.92393002,  0.3576374 ,  0.71279398,  0.34643582,  0.88350439,
       -0.56464465, -0.90440042, -0.05049994, -0.69786988, -0.06951832,
       -0.18681777, -0.6249326 , -0.19045464,  0.96664411, -0.61806869,
       -0.88451874, -0.20683923,  0.85247773, -0.39973071, -0.13265934,
        0.72795847, -0.02343472,  0.33867728, -0.98195484,  0.54184388,
        0.27002303, -0.29806969, -0.43726981,  0.36133784, -0.84715094,
       -0.69332228, -0.83106504, -0.28346687,  0.98262242,  0.5119561 ,
       -0.93214313, -0.77475742,  0.45817369, -0.48806544, -0.10375762,
        0.45386039, -0.99914272,  0.16330127,  0.77013124, -0.53340043,
        0.28783771,  0.44268808, -0.90805792,  0.3919344 ,  0.16533973,
       -0.15064575, -0.98263444, -0.52304174,  0.16056292,  0.10674647,
        0.62903702,  0.72387046,  0.54983823,  0.92656862, -0.16712893,
       -0.02562563, -0.69147331,  0.86617033,  0.38888283, -0.02799532,
       -0.29473042,  0.77624045, -0.08323858,  0.28268795, -0.90

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 1.75159296  5.69993553  0.25940545  9.94669318  4.41498774 11.49267594
  9.8752963   6.24357427  7.81310653  7.44573188]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[7.26444613e+00 2.10430027e+00 9.86316323e+00 8.02242412e+00
  1.50657946e+01 2.42178952e+00 2.69632901e+00 2.47805072e+00
  1.28700942e+01 1.69355949e+00]
 [4.74733373e+00 8.75642589e+00 1.00243893e+01 1.88968697e+00
  3.33598528e+00 9.32065824e+00 1.00006272e+01 7.50406459e+00
  1.52021272e+01 5.10448576e-01]
 [6.76393105e+00 9.79401822e+00 1.21461271e+01 3.56831664e+00
  2.95647535e+00 9.47659151e+00 1.18135979e+01 8.83182149e+00
  1.73274798e+01 1.62216383e+00]
 [3.70759190e+00 5.63763212e+00 8.33324099e+00 1.88239524e+00
  6.12560872e+00 6.70294083e+00 7.03228178e+00 4.34543501e+00
  1.30467343e+01 2.42729841e+00]
 [3.00812673e+00 5.83908928e+00 5.86579768e-01 1.04359728e+00
  1.54422226e+01 1.69330350e+00 5.31847543e+00 7.75682250e+00
  2.67944247e+00 1.20666043e+01]
 [4.28353922e+00 3.31239341e+00 8.33329266e+00 3.23255595e+00
  8.64907798e+00 4.17307655e+00 5.48676227e+00 2.21444327e+00
  1.25786803e+01 2.64745206e+00]
 [1.21608489e-01 4.06174094e+00 4.39553732e+00 1.43603268e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[8 7 0 8 0 3 5 0 4 2]
 [3 0 2 8 8 6 0 1 9 5]
 [3 7 3 7 8 3 1 8 2 7]
 [1 7 4 4 1 0 2 8 4 3]
 [7 9 0 6 9 9 5 8 4 7]
 [7 6 0 6 9 1 2 1 5 7]
 [8 5 9 8 7 4 8 9 2 5]
 [8 4 2 7 8 0 7 4 7 2]
 [1 0 1 6 9 7 1 3 5 2]
 [4 6 5 7 3 6 3 9 3 4]]
[[0 0 0 0 0]
 [0 8 7 0 8]
 [0 3 0 2 8]
 [0 3 7 3 7]
 [0 1 7 4 4]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)
Z = np.arange(1, 15, dtype=np.uint32)
print(sliding_window_view(Z, window_shape=4))


[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]
[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
Z = np.random.uniform(0,1,(10,10))
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
rank = np.sum(S > 1e-10)
print(rank)

rank = np.linalg.matrix_rank(Z)
print(rank)

10
10


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
Z = np.random.randint(0,10,50)
print(np.bincount(Z).argmax())

3


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)
Z = np.random.randint(0,5,(10,10))
print(sliding_window_view(Z, window_shape=(3, 3)))

[[[[3 4 1]
   [2 2 0]
   [2 1 4]]

  [[4 1 2]
   [2 0 4]
   [1 4 1]]

  [[1 2 2]
   [0 4 3]
   [4 1 2]]

  [[2 2 4]
   [4 3 2]
   [1 2 4]]

  [[2 4 3]
   [3 2 4]
   [2 4 2]]

  [[4 3 1]
   [2 4 1]
   [4 2 3]]

  [[3 1 1]
   [4 1 0]
   [2 3 2]]

  [[1 1 3]
   [1 0 2]
   [3 2 4]]]


 [[[2 2 0]
   [2 1 4]
   [2 2 1]]

  [[2 0 4]
   [1 4 1]
   [2 1 1]]

  [[0 4 3]
   [4 1 2]
   [1 1 2]]

  [[4 3 2]
   [1 2 4]
   [1 2 2]]

  [[3 2 4]
   [2 4 2]
   [2 2 3]]

  [[2 4 1]
   [4 2 3]
   [2 3 1]]

  [[4 1 0]
   [2 3 2]
   [3 1 1]]

  [[1 0 2]
   [3 2 4]
   [1 1 2]]]


 [[[2 1 4]
   [2 2 1]
   [3 1 2]]

  [[1 4 1]
   [2 1 1]
   [1 2 1]]

  [[4 1 2]
   [1 1 2]
   [2 1 3]]

  [[1 2 4]
   [1 2 2]
   [1 3 3]]

  [[2 4 2]
   [2 2 3]
   [3 3 0]]

  [[4 2 3]
   [2 3 1]
   [3 0 3]]

  [[2 3 2]
   [3 1 1]
   [0 3 4]]

  [[3 2 4]
   [1 1 2]
   [3 4 2]]]


 [[[2 2 1]
   [3 1 2]
   [1 1 4]]

  [[2 1 1]
   [1 2 1]
   [1 4 3]]

  [[1 1 2]
   [2 1 3]
   [4 3 1]]

  [[1 2 2]
   [1 3 3]
   [3 1 3]]

  [[2 2 3]
   

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0 16  8 12 10]
 [16  4  6 12  6]
 [ 8  6  3 42 10]
 [12 12 42  3  9]
 [10  6 10  9  4]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
Z = np.ones((16,16))
k = 4
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)
Z = np.ones((16,16))
k = 4
windows = np.lib.stride_tricks.sliding_window_view(Z, (k, k))
S = windows[::k, ::k, ...].sum(axis=(-2, -1))
Z = np.ones((16, 16))
k = 4
print(sliding_window_view(Z, window_shape=(k, k))[::k, ::k].sum(axis=(-2, -1)))

[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
 Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9998 9999 9997 9996 9995]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.88 s ± 240 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
144 ms ± 806 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
125 ms ± 662 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 2 3 4 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[1 1 3]
 [3 2 2]
 [4 3 1]
 [1 3 4]
 [0 2 2]
 [3 3 0]
 [2 4 2]
 [2 3 4]
 [3 4 4]
 [0 2 0]]
[[1 1 3]
 [3 2 2]
 [4 3 1]
 [1 3 4]
 [0 2 2]
 [3 3 0]
 [2 4 2]
 [2 3 4]
 [3 4 4]
 [0 2 0]]
[[1 1 3]
 [3 2 2]
 [4 3 1]
 [1 3 4]
 [0 2 2]
 [3 3 0]
 [2 4 2]
 [2 3 4]
 [3 4 4]
 [0 2 0]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)
uZ = np.unique(Z, axis=0)
print(uZ)

[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]
[[0 0 0]
 [0 1 0]
 [1 0 0]
 [1 1 1]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[3.79066686e-02, 2.53983003e-04, 7.82799242e-02, 1.07254975e-01,
        2.07906602e-02, 1.36163041e-01, 7.54182457e-02, 5.74081375e-02,
        2.00503933e-01, 2.15009755e-01],
       [1.82285020e-02, 1.22134966e-04, 3.76431327e-02, 5.15766119e-02,
        9.99778154e-03, 6.54778790e-02, 3.62670130e-02, 2.76063392e-02,
        9.64180307e-02, 1.03393569e-01],
       [7.49207637e-02, 5.01985569e-04, 1.54716622e-01, 2.11984460e-01,
        4.10917710e-02, 2.69119904e-01, 1.49060648e-01, 1.13464508e-01,
        3.96286678e-01, 4.24956760e-01],
       [4.79215054e-02, 3.21084609e-04, 9.89612634e-02, 1.35591443e-01,
        2.62834951e-02, 1.72136939e-01, 9.53435373e-02, 7.25752085e-02,
        2.53476516e-01, 2.71814737e-01],
       [1.57687755e-01, 1.05654259e-03, 3.25636254e-01, 4.46169420e-01,
        8.64869604e-02, 5.66423932e-01, 3.13731972e-01, 2.38811816e-01,
        8.34075276e-01, 8.94417973e-01],
       [1.09932689e-01, 7.36573158e-04, 2.27018699e-01, 3.11048908e-01,
   

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.12259012  0.29737675]
